INSERT INTO Tasks (TaskCreatedBy,
                   TaskTitle,
                   TaskDescription,
                   TaskProjectId,
                   TaskStatus,
                   TaskType,
                   TaskPriority,
                   TaskDeleted,
                   TaskCreatedDate,
                   TaskUpdatedDate,
                   TaskDueDate)
VALUES (@TaskCreatedBy,
        @TaskTitle,
        @TaskDescription,
        @TaskProjectId,
        @TaskStatus,
        @TaskType,
        @TaskPriority,
        @TaskDeleted,
        @TaskCreatedDate,
        @TaskUpdatedDate,
        @TaskDueDate);
